-- Retrive list of unique countries --

Select Distinct country from gold.dim_customers;

-- Show the first and last order and total duraction on months --

Select 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(month, min(order_date), max(order_date)) AS datedifference
FROM gold.fact_sales;

-- Find the youngest and oldest customers based on birthday --

Select
	Max(birthdate) AS youngest_customer,
	DATEDIFF(YEAR, MAX(birthdate), GETDATE()) As youngest_customer_age,
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(YEAR, MIN(birthdate), GETDATE()) As oldest_customer_age
	from gold.dim_customers;

-- Total Customers by country --

SELECT 
	Country, 
	SUM(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER By count(customer_key) desc;

-- Find total customer by gender -- ?

Select gender, Count(customer_key) AS total_customers
from gold.dim_customers
group by gender
order by count(customer_key)desc;

-- Find total products by category -- ?

Select category, Count(product_key) AS total_customers
from gold.dim_products
group by category
order by count(product_key)desc;

-- What is the avg and total revenue generated by each category --

Select
	p.Category,
	AVG(p.cost) AS total_cost_cat,
	SUM(f.sales_amount) AS total_sales_by_cat
from gold.dim_products p
left join gold.fact_sales f
ON p.product_key = f.product_key
group by p.category
order by total_sales_by_cat DESC;

-- What is the total revenue generated by each customer --

Select c.customer_key,
	c.first_name,
	SUM(s.sales_amount) as total_sales_by_cust
	from gold.dim_customers c
	left join gold.fact_sales s
ON c.customer_key = s.customer_key
Group by c.customer_key,c.first_name
order by total_sales_by_cust DESC;

-- What is the distribution of sold items across countries --

Select
	c.country,
	SUM(f.quantity) As total_sold_items
	from gold.dim_customers c
	left join gold.fact_sales f
	On c.customer_key = f.customer_key
Group by c.country
Order by total_sold_items;


